# Generated by Django 5.0 on 2024-06-17 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('dia_chi', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('dien_thoai', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('dia_chi', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('dien_thoai', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NhaSanXuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('dia_chi', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('dien_thoai', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nhan_vien_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_kho', models.CharField(max_length=100)),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kho', to='app.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuXuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.IntegerField(default=0)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.khachhang')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('mo_ta', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gia', models.IntegerField()),
                ('loai_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loaihang')),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nhacungcap')),
                ('nha_san_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nhasanxuat')),
            ],
        ),
        migrations.CreateModel(
            name='TonKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0)),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_kho', to='app.kho')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietXuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('gia', models.IntegerField()),
                ('phieu_xuat_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_xuat', to='app.phieuxuatkho')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sanpham')),
            ],
            options={
                'unique_together': {('phieu_xuat_kho', 'san_pham')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('tong_tien', models.IntegerField()),
                ('phieu_nhap_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_nhap', to='app.phieunhapkho')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sanpham')),
            ],
            options={
                'unique_together': {('phieu_nhap_kho', 'san_pham')},
            },
        ),
    ]
