# Generated by Django 5.0 on 2024-06-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonVi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_don_vi', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='chitietnhapkho',
            name='don_vi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.donvi'),
        ),
        migrations.AddField(
            model_name='chitietxuatkho',
            name='don_vi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.donvi'),
        ),
        migrations.AddField(
            model_name='tonkho',
            name='don_vi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.donvi'),
        ),
    ]
