# Generated by Django 5.0 on 2024-06-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_donvi_chitietnhapkho_don_vi_chitietxuatkho_don_vi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietnhapkho',
            name='don_vi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.donvi'),
        ),
        migrations.AlterField(
            model_name='chitietxuatkho',
            name='don_vi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.donvi'),
        ),
        migrations.AlterField(
            model_name='tonkho',
            name='don_vi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.donvi'),
        ),
    ]
