# Generated by Django 5.0 on 2024-06-17 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_chitietnhapkho_don_vi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kho',
            name='nhan_vien',
        ),
        migrations.AddField(
            model_name='kho',
            name='dia_chi',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='kho',
            name='nhan_vien_quan_ly',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
