# Generated by Django 5.0 on 2024-06-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_kho_nhan_vien_kho_dia_chi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kho',
            name='dia_chi',
            field=models.CharField(max_length=255),
        ),
    ]
