# Generated by Django 5.0 on 2024-06-17 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_kho_dia_chi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kho',
            name='nhan_vien_quan_ly',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nhanvien'),
        ),
    ]
