# Generated by Django 5.0 on 2024-06-17 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_chitietnhapkho_kho_alter_kho_nhan_vien_quan_ly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietnhapkho',
            name='kho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kho'),
        ),
    ]
