# Generated by Django 5.0 on 2024-06-17 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_chitietnhapkho_kho'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietxuatkho',
            name='kho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.kho'),
        ),
    ]
