# Generated by Django 5.0 on 2024-06-17 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_chitietxuatkho_kho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietxuatkho',
            name='kho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kho'),
        ),
    ]
