# Generated by Django 5.0 on 2024-06-17 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_chitietxuatkho_kho'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuChuyenKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.IntegerField(default=0)),
                ('kho_chuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phieu_chuyen_kho', to='app.kho')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietChuyenKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('don_vi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.donvi')),
                ('kho_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_nhan', to='app.kho')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sanpham')),
                ('phieu_chuyen_kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_chuyen', to='app.phieuchuyenkho')),
            ],
            options={
                'unique_together': {('phieu_chuyen_kho', 'san_pham')},
            },
        ),
    ]
