# Generated by Django 5.0 on 2024-06-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_phieuchuyenkho_chitietchuyenkho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phieuchuyenkho',
            name='tong_tien',
        ),
    ]
