# Generated by Django 5.0.6 on 2024-06-18 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_phieuchuyenkho_kho_chuyen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kho',
            name='nhan_vien_quan_ly',
        ),
        migrations.AlterField(
            model_name='chitietchuyenkho',
            name='kho_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kho'),
        ),
    ]
